/*
Propriété du 
Club Chinook/ETS
*/
/******************************************************************
					Global.h
******************************************************************/

#ifndef MOTOR_GLOBAL
#define MOTOR_GLOBAL
/******************************************************************
						Select module
******************************************************************/
//!!!!!!!!!!!!!!!!!!!!!!ALIM!!!!!!!!!!!!!!!!!!!
	//5V generated by firstSepic to power the actuators
//#define USE_ACTUATOR_ALIM	
	//Flyback control to Generate 5V onboard and
#define USE_LOGIC_ALIM	
	//12 generated by second Sepic to power sensors and bootstrap
#define USE_HV_ALIM

//!!!!!!!!!!!!!!!!!!!!!!MOTORS!!!!!!!!!!!!!!!!!
#define USE_QEI1
#define USE_TOWER_CONTROL
#define USE_ACTU
/******************************************************************
						Timing define
******************************************************************/
#define FOSC_MHZ 		110.0f  		//F en MHz (pas plus haut que 120Mhz)
#define FOSC			FOSC_MHZ*1000000.0f
#define BAUDRATE 		115200.0f  		//Baudrate of UART

#define FREQ_TMR3		2000.0f			//Refresh rate of alim control loop
#define FREQ_TMR5		8.0f			//Refrsh rate of motor control loop
#define FREQ_STEPPER	40E3f
#define FREQ_MAT		40E3f

/******************Memory*************/
#define NUM_OF_ECAN_BUFFERS 32
/******************************************************************
							IO
******************************************************************/
#define LED1	_RA2
#define LED2	_RA3
#define LED3	_RA4
/**************************************************************
					Calculus Constant
***************************************************************/
//All const float are define in main
//Const should be define as extern

#define	MAT_COUNT_MAX 49000 //49*20*50

extern float Mat_Pos_Ref;
extern float Mat_Pos;

extern const float GM5;
#endif


